### ISSUE TITLE
problems with kancollection waiting to load when game started 

### ISSUE THREAD

**Issue by GLee338** [Yuubari/KanColleViewer#15]
hi
I am having the problem on the bottom state  waiting Kancollection to start when I hit the start the information doesn't show 

thanks

**Comment by Yuubari** [comment]
You are having the problem of not updating to the latest version and reporting issues that were already reported: #14.

**Comment by GLee338** [comment]
hi
how would I fix it sorry 
thanks

**Comment by Yuubari** [comment]
Which version of KCV are you using? The version number from the right pane, 4.x.x, what is it?

**Comment by GLee338** [comment]
hi
version 3.8.2 rev. 561
thanks

**Comment by Yuubari** [comment]
Why are you asking this here, then?

**Comment by GLee338** [comment]
Hi
It was link to this website if so then where would I download your verision

**Comment by Yuubari** [comment]
You probably won't believe me. It's incredibly hard and basically impossible to find the downloads area. You have to open the main page of this repository and read the lines above the file list.

Think of it as of an IQ test of sorts.

I mean, you were already gifted enough to ask questions about [gakada's KCV](https://github.com/gakada/KanColleViewer) here instead of his own repository's issues page.

**Comment by GLee338** [comment]
Hi 
Thanks anyway
