### ISSUE TITLE
Quest details 

### ISSUE THREAD

**Issue by darkzo1** [Yuubari/KanColleViewer#20]

**Comment by itsukarine** [comment]
Since Darkzo dropped the ball here, I'm gonna hijack; is there any intent on fixing the new quest log functionality? The quests only come up in KCV if you hunt through "all" to find them and I actually found it more beneficial in 4.2.4 to open up the "active" quest tab in game to put them in KCV's quest area each time I went to do something. I didn't really test out if this an issue for me or with the program, so excuse me if it's some stupidly simple shit to fix. 

Also, how do translations work? The new quests seem to be untranslated, dunno if that's supposed to happen or not.

**Comment by Yuubari** [comment]
There is no way to “fix” it due to the way the game sends quest information.

Translations for new quests will be out a bit later.

**Comment by itsukarine** [comment]
Thanks.

**Comment by Ech0Sierra** [comment]
The loss of quest loading from tabs other than "全　All" is exclusive to the latest release, I tried to replicate it on 4.2.4 and the quests work just fine. Grabacr did something to mess it up?

**Comment by Yuubari** [comment]
The way KCV works is that every time it receives a page of quests with a different-to-before content, it empties its current stored pages. Subsets of quests trigger this clean-up, but do not contain all of the active quests.

Though it's more convoluted than this. Sadly, the way the game communicates the quest list to the client leaves a lot to be desired, as the game client itself does not need to keep all quests stored locally.
