### ISSUE TITLE
Viewer will not translate text

### ISSUE THREAD

**Issue by cpang6** [Yuubari/KanColleViewer#25]
I just reset my Windows 10 computer and now I'm unable to see any translations for the ship names, equipment, expeditions, quests, etc. Does anyone have any idea what I should do?

**Comment by Yuubari** [comment]
I'm guessing WebClient does not get properly redirected to HTTPS.

Removed forced TLS, should work now.

**Comment by cpang6** [comment]
The entire program is contained and doesn't update from any server, right? Because the text started working again yesterday. I'm not sure if it's from what you did or something just finally worked.

The weird thing is that I copied the entire program from my laptop (which translated fine) onto my desktop and it didn't work there. Just a note.

All aside, it works now and regardless of how it was done, thank you.

**Comment by Yuubari** [comment]
KCV updates translations from my server; a few days ago I changed the settings on the server so everything was served over HTTPS instead of HTTP. Sadly, the WebClient class used by KCV for fetching updates did not seem to like that change; I reverted the configuration changes and now it works again.

**Comment by cpang6** [comment]
At least the problem has been resolved
