### ISSUE TITLE
Hamakaze disconnects my game

### ISSUE THREAD

**Issue by CptBrown** [Yuubari/KanColleViewer#36]
Recently, everytime I try to access fleet 2 of my game, it instantly disconnects the game. This only happens in KCV. I have tested the latest version, the version before and even the original one. After switching to VPN and accessing the game through Google Chrome, I have found that it's possible to access fleet 2 from there. However, I wanted to test if it's the fleet's problem or a ship's, so I went back to KCV and tried to remove the ships 1 by 1 by switching them out of fleet 2 with an empty slot. Turns out, when I click on Hamakaze, the game instantly disconnects. With VPN, I removed Hamakaze from fleet 2 and there doesn't seem to be a problem since. Any help regarding this issue?

**Comment by Yuubari** [comment]
Did you check if this happens in Internet Explorer or in KCV only?

**Comment by CptBrown** [comment]
I just went to try it out, and there doesn't seem to be a problem with Internet Explorer.

**Comment by Yuubari** [comment]
When you say “disconnect” do you mean the error cat screen? You didn't provide enough details, but there's really zero reason for a disconnect if it's the error cat, because KCV runs the game inside a copy of Internet Explorer and does not alter the data flow in any way.

I'm unable to reproduce this issue with my own Hamakaze.

**Comment by CptBrown** [comment]
Yes, it is the cat screen disconnect. I have also tried a lot of ways to click on her, such as the fleet changing menu, equipment changing menu and even the docking menu, all of which failing and giving me the error cat screen. However, I can still access her through the gallery.
![image](https://cloud.githubusercontent.com/assets/10834411/6026537/94ae1310-ac16-11e4-9d31-785cf48e2ba8.png)

**Comment by Yuubari** [comment]
Try clearing Internet Explorer's cache, it may or may not help.

Other than that I have no idea, it's not really related to KCV. Maybe you've stumbled into some weird bug in the FiddlerCore library used by KCV, maybe it's something with Flash, maybe it's the IE browser control issue. There's no real way to diagnose this. You could try using Fiddler itself to check what happens when you try to interact with Hamakaze (as in, what the server returns).

You're using the cookie method with KCV, right?

**Comment by CptBrown** [comment]
Yes, I do use the "set region cookie" function to play the game since I'm not in Japan.

As for clearing the cache, I tried using the one in KCV but it did not work. Thus, I switched to Internet Explorer and cleared everything, cookies, caches, passwords and whatnot. This solved the problem and I am now able to access Hamakaze again without disconnecting.

Thanks for the immediate replies and help!
![image](https://cloud.githubusercontent.com/assets/10834411/6026753/49be7bd6-ac18-11e4-862c-f17d64339972.png)
