### ISSUE TITLE
Game requires new API on every boot

### ISSUE THREAD

**Issue by Grimalkinii** [Yuubari/KanColleViewer#6]
I didn't have this problem before, but it seems to be a recent thing and I haven't changed any network settings or settings in the viewer, on DMM itself -- but every time I boot the viewer, if I'm not using a brand-new API, KanColle gives me the cat error message. Upon putting a new one into the config, the game works fine, but only until I close it and try to reopen it using the same API token.

**Comment by Yuubari** [comment]
As you very well know, anything related to API token expiration is within DMM's realm.

This change is at least 2 months old now. You might want to ask DMM themselves about this issue, as all KCV does is go to the link provided. KCV itself does not invalidate tokens.

Use the region cookie method.

To be quite honest I am not sure why you are reporting this issue here; I do not work for DMM.
