### ISSUE TITLE
KVC.Landscape plugin stopped working

### ISSUE THREAD

**Issue by tainothewarden** [Yuubari/KanColleViewer#62]

**Comment by Yuubari** [comment]
Can you please provide answers to the following questions so I can understand better what is happening:

1. Why are you reporting this here, and not to KCV.Landscape's developer;
2. Do I look like KCV.Landscape's developer;
3. Why should I look into this, considering said KCV.Landscape has not been updated since January, and is probably broken due to KCV's model set changes and API changes?

Many thanks in advance.

**Comment by Yuubari** [comment]
Regarding this plug-in, people report it working fine with 3.8.0.7, so it's your local issue I guess…
